export const OFFER_BY_ID={
	"offerId": "offer-204",
	"userId": "pooja@gmail.com",
	"offerTitle": "Women Printed Maxi Dress",
	"offerValidity": "2018-04-24T10:04:31.66",
	"dateOfAnnouncement": "2018-04-24T10:04:31.66",
	"address": {
		"name": "Only for You",
		"number": null,
		"street": "Sector 21",
		"city": "Gurgaon",
		"state": "Harayana",
		"zipCode": 122016
	},
	"offerDescription": "Navy and white printed woven maxi dress, has a round neck, three-quarter sleeves, hook and eye closures, flared hem, Cotton made and Machine-washable",
	"originalPrice": 1995,
	"discount": 35,
	"offerRating": 4.5,
	"offerCategories": "Clothing",
	"offerTerms": "5 days return policy",
	"keywords": "navy, white, maxi dress, dress, women, women dress",
	"imageURL": "printed maxi dress"
}

export const RELATED_PRODUCTS=[
{
	"_id": "offer-204",
	"userId": "pooja@gmail.com",
	"offerTitle": "Women Printed Maxi Dress",
	"offerValidity": "2018-04-24T04:34:31.660+0000",
	"dateOfAnnouncement": "2018-04-24T04:34:31.660+0000",
	"address": {
		"name": "Only for You",
		"street": "Sector 21",
		"city": "Gurgaon",
		"state": "Harayana",
		"zipCode": 122016
	},
	"offerDescription": "Navy and white printed woven maxi dress, has a round neck, three-quarter sleeves, hook and eye closures, flared hem, Cotton made and Machine-washable",
	"originalPrice": 1995,
	"discount": 35,
	"offerRating": 4.5,
	"offerCategories": "Clothing",
	"offerTerms": "5 days return policy",
	"keywords": "navy, white, maxi dress, dress, women, women dress",
	"imageURL": "printed maxi dress",
	"_class": "com.offershopper.offerdatabaseservice.model.OfferBean",
	"score": 1
},
{
	"_id": "offer-205",
	"userId": "sharanghotra@gmail.com",
	"offerTitle": "Women Floral Print Belted Maxi Dress",
	"offerValidity": "2018-04-24T04:34:31.660+0000",
	"dateOfAnnouncement": "2018-04-24T04:34:31.660+0000",
	"address": {
		"name": "Sports4U",
		"street": "garhi cantt",
		"city": "Dehradun",
		"state": "Uttarakhand",
		"zipCode": 248003
	},
	"offerDescription": "Dusty pink and green floral print woven belted maxi dress, has shoulder straps, an attached lining, flared hem 100% Original Products Material & Care Polyester Machine-wash",
	"originalPrice": 2299,
	"discount": 40,
	"offerRating": 3.5,
	"offerCategories": "Clothing",
	"offerTerms": "10 days return policy",
	"keywords": "Dusty pink, pink, green floral, print woven, belted maxi, belted maxi dress, shoulder strap, attatched lining ",
	"_class": "com.offershopper.offerdatabaseservice.model.OfferBean",
	"score": 1
},
{
	"_id": "offer-206",
	"userId": "pooja@gmail.com",
	"offerTitle": " Women Multicoloured Printed Shorts",
	"offerValidity": "2018-04-24T04:34:31.660+0000",
	"dateOfAnnouncement": "2018-04-24T04:34:31.660+0000",
	"address": {
		"name": "Only for You",
		"street": "Sector 21",
		"city": "Gurgaon",
		"state": "Harayana",
		"zipCode": 122016
	},
	"offerDescription": "A pair of multicoloured woven mid-rise printed shorts, has a waistband with belt loops, zip fly and button closure, pleat detailing below the waistband on the front, two slants pockets on the front sides Material & Care Crepe Hand-wash",
	"originalPrice": 999,
	"discount": 60,
	"offerRating": 4.5,
	"offerCategories": "Clothing",
	"offerTerms": "5 days return policy",
	"keywords": "multicoloured woven, mid-rise printed shorts, belt loops, waistband belt loops, button closure, pleat detailing, two slant pockets, pockets, slant pockets",
	"imageURL": "printed multicolor shorts, shorts",
	"_class": "com.offershopper.offerdatabaseservice.model.OfferBean",
	"score": 1
},
{
	"_id": "offer-207",
	"userId": "pooja@gmail.com",
	"offerTitle": "Roadster Men Regular Fit Regular Shorts",
	"offerValidity": "2018-04-24T04:34:31.660+0000",
	"dateOfAnnouncement": "2018-04-24T04:34:31.660+0000",
	"address": {
		"name": "Only for You",
		"street": "Sector 21",
		"city": "Gurgaon",
		"state": "Harayana",
		"zipCode": 122016
	},
	"offerDescription": "Charcoal grey solid mid-rise regular shorts, has 4 pockets, a button closure Material & Care 100% cotton Machine-wash ",
	"originalPrice": 999,
	"discount": 20,
	"offerRating": 4.5,
	"offerCategories": "Clothing",
	"offerTerms": "30 days return policy",
	"keywords": "Charcoal Grey Solid, Regular Fit, Regular Shorts, cotton, button closure, pockets, mid-rise, shorts",
	"imageURL": "roadstar shorts",
	"_class": "com.offershopper.offerdatabaseservice.model.OfferBean",
	"score": 1
},
{
	"_id": "offer-208",
	"userId": "pooja@gmail.com",
	"offerTitle": "Formal Shirt",
	"offerValidity": "2018-04-24T04:34:31.660+0000",
	"dateOfAnnouncement": "2018-04-24T04:34:31.660+0000",
	"address": {
		"name": "Only for You",
		"street": "Sector 21",
		"city": "Gurgaon",
		"state": "Harayana",
		"zipCode": 122016
	},
	"offerDescription": "Purple solid formal shirt, has a spread collar, button placket, 1 pocket, long sleeves, curved hem Material & Care Cotton and polyester Machine-wash ",
	"originalPrice": 995,
	"discount": 40,
	"offerRating": 4.5,
	"offerCategories": "Clothing",
	"offerTerms": "30 days return policy",
	"keywords": "Purple solid formal,  spread collar,  1 pocket",
	"imageURL": "Solid Formal Shirt",
	"_class": "com.offershopper.offerdatabaseservice.model.OfferBean",
	"score": 1
},
{
	"_id": "offer-217",
	"userId": "pooja@gmail.com",
	"offerTitle": "Magnetic Designs Women Black Jumpsuit",
	"offerValidity": "2018-04-24T04:34:31.660+0000",
	"dateOfAnnouncement": "2018-04-24T04:34:31.660+0000",
	"address": {
		"name": "Only for You",
		"street": "Sector 21",
		"city": "Gurgaon",
		"state": "Harayana",
		"zipCode": 122016
	},
	"offerDescription": "Black jumpsuit, boat neck, three quarter length sleeves, box pleats at the front, elasticated at the waist, pocket on the sides of the waist, button and loop closure at the back",
	"originalPrice": 819,
	"discount": 8,
	"offerRating": 4,
	"offerCategories": "Clothing",
	"offerTerms": "7 days return policy",
	"keywords": "Jumpsuits, black jumpsuits, clothing jumpsuits, quarter length sleeves",
	"imageURL": "magnetic Jumpsuits",
	"_class": "com.offershopper.offerdatabaseservice.model.OfferBean",
	"score": 1
},
{
	"_id": "offer-102",
	"userId": "sharanghotra@gmail.com",
	"offerTitle": "jeans",
	"offerValidity": "2018-04-24T04:34:31.660+0000",
	"dateOfAnnouncement": "2018-04-24T04:34:31.660+0000",
	"address": {
		"name": "Sports4U",
		"street": "garhi cantt",
		"city": "Dehradun",
		"state": "Uttarakhand",
		"zipCode": 123456
	},
	"offerDescription": "Blue medium wash 5-pocket mid-rise jeans, clean look with light fade, has a button and zip closure, 98% Cotton 2% Elastane Machine-wash by Highlander",
	"originalPrice": 1699,
	"discount": 55,
	"offerRating": 4.5,
	"offerCategories": "Clothing",
	"offerTerms": "10 days return policy",
	"keywords": "low waist,blue jeans, jeans, Highlander, men jeans, straight leg,slim ",
	"score": 1
},
{
	"_id": "offer-203",
	"userId": "pooja@gmail.com",
	"offerTitle": "Women Skinny Fit Jeans",
	"offerValidity": "2018-04-24T04:34:31.660+0000",
	"dateOfAnnouncement": "2018-04-24T04:34:31.660+0000",
	"address": {
		"name": "Only for You",
		"street": "Sector 21",
		"city": "Gurgaon",
		"state": "Harayana",
		"zipCode": 122016
	},
	"offerDescription": "Black dark wash 5-pocket mid-rise jeans, clean look with no fade, has a button and zip closure, waistband with belt loops by Here and Now. Material: 80% cotton, 18% polyester, 2% elastane Machine-wash",
	"originalPrice": 1699,
	"discount": 40,
	"offerRating": 4.5,
	"offerCategories": "Clothing",
	"offerTerms": "5 days return policy",
	"keywords": "High waist,here and now, women jeans, straight leg,skinny, black jeans, jeans ",
	"_class": "com.offershopper.offerdatabaseservice.model.OfferBean",
	"score": 1
},
{
	"_id": "offer-201",
	"userId": "pooja@gmail.com",
	"offerTitle": "Women Skinny Fit Jeans",
	"offerValidity": "2018-04-24T04:34:31.660+0000",
	"dateOfAnnouncement": "2018-04-24T04:34:31.660+0000",
	"address": {
		"name": "Only for You",
		"street": "Sector 21",
		"city": "Gurgaon",
		"state": "Harayana",
		"zipCode": 122016
	},
	"offerDescription": "Blue dark wash 5-pocket mid-rise jeans, clean look with no fade, has a button and zip closure, waistband with belt loops by Forever 21. Material: 80% cotton, 18% polyester, 2% elastane Machine-wash",
	"originalPrice": 1299,
	"discount": 5,
	"offerRating": 4.5,
	"offerCategories": "Clothing",
	"offerTerms": "30 days return policy",
	"keywords": "High waist,Forever 21, women jeans, straight leg,skinny ",
	"_class": "com.offershopper.offerdatabaseservice.model.OfferBean",
	"score": 1
},
{
	"_id": {
		"timestamp": 1525184260,
		"machineIdentifier": 15439796,
		"processIdentifier": 15767,
		"counter": 2473515,
		"timeSecond": 1525184260,
		"time": 1525184260000,
		"date": "2018-05-01T14:17:40.000+0000"
	},
	"userId": "megha@gmail.com",
	"offerTitle": "Informal Shirt",
	"offerValidity": "2018-04-24T04:34:31.660+0000",
	"dateOfAnnouncement": "2018-04-24T04:34:31.660+0000",
	"address": {
		"name": "Only for You",
		"street": "Sector 21",
		"city": "Gurgaon",
		"state": "Harayana",
		"zipCode": 122016
	},
	"offerDescription": "Purple solid formal shirt, has a spread collar, button placket, 1 pocket, long sleeves, curved hem Material & Care Cotton and polyester Machine-wash ",
	"originalPrice": 995,
	"discount": 40,
	"offerRating": 4.5,
	"offerCategories": "Clothing",
	"offerTerms": "30 days return policy",
	"keywords": "Purple solid formal,  spread collar,  1 pocket",
	"imageURL": "Solid Formal Shirt",
	"_class": "com.offershopper.offerdatabaseservice.model.OfferBean",
	"score": 1
}
]

export const PRODUCTS_OF_A_VENDOR=[
{
	"offerId": "5ae85e41eb97b43d97258b62",
	"userId": "megha@gmail.com",
	"offerTitle": "Formal Shirt",
	"offerValidity": "2018-04-24T10:04:31.66",
	"dateOfAnnouncement": "2018-04-24T10:04:31.66",
	"address": {
		"name": "Only for You",
		"number": null,
		"street": "Sector 21",
		"city": "Gurgaon",
		"state": "Harayana",
		"zipCode": 122016
	},
	"offerDescription": "Purple solid formal shirt, has a spread collar, button placket, 1 pocket, long sleeves, curved hem Material & Care Cotton and polyester Machine-wash ",
	"originalPrice": 995,
	"discount": 40,
	"offerRating": 4.5,
	"offerCategories": null,
	"offerTerms": "30 days return policy",
	"keywords": "Purple solid formal,  spread collar,  1 pocket",
	"imageURL": "image_url"
},
{
	"offerId": "5ae87704eb97b43d9725be2b",
	"userId": "megha@gmail.com",
	"offerTitle": "Informal Shirt",
	"offerValidity": "2018-04-24T10:04:31.66",
	"dateOfAnnouncement": "2018-04-24T10:04:31.66",
	"address": {
		"name": "Only for You",
		"number": null,
		"street": "Sector 21",
		"city": "Gurgaon",
		"state": "Harayana",
		"zipCode": 122016
	},
	"offerDescription": "Purple solid formal shirt, has a spread collar, button placket, 1 pocket, long sleeves, curved hem Material & Care Cotton and polyester Machine-wash ",
	"originalPrice": 995,
	"discount": 40,
	"offerRating": 4.5,
	"offerCategories": "Clothing",
	"offerTerms": "30 days return policy",
	"keywords": "Purple solid formal,  spread collar,  1 pocket",
	"imageURL": "Solid Formal Shirt"
},
{
	"offerId": "5aea94d0ee9f6508c77be6d4",
	"userId": "megha@gmail.com",
	"offerTitle": "vc",
	"offerValidity": "2018-12-31T10:20:14",
	"dateOfAnnouncement": "2018-04-24T10:04:31.66",
	"address": {
		"name": "Megha Cafe",
		"number": "874",
		"street": "garhi cantt",
		"city": "Dehradun",
		"state": "Uttarakhand",
		"zipCode": 248003
	},
	"offerDescription": "vc",
	"originalPrice": 3,
	"discount": 3,
	"offerRating": 0,
	"offerCategories": "vc",
	"offerTerms": "vc",
	"keywords": "vc",
	"imageURL": null
},
{
	"offerId": "5aea95b3ee9f6508c77be6d6",
	"userId": "megha@gmail.com",
	"offerTitle": "gb",
	"offerValidity": "2018-12-31T10:24:01",
	"dateOfAnnouncement": "2018-04-24T10:04:31.66",
	"address": {
		"name": "Megha Cafe",
		"number": "874",
		"street": "garhi cantt",
		"city": "Dehradun",
		"state": "Uttarakhand",
		"zipCode": 248003
	},
	"offerDescription": "gb",
	"originalPrice": 3,
	"discount": 3,
	"offerRating": 0,
	"offerCategories": "gb",
	"offerTerms": "gb",
	"keywords": "gb",
	"imageURL": null
},
{
	"offerId": "5aebdc7b80aff11139e76059",
	"userId": "megha@gmail.com",
	"offerTitle": "bin",
	"offerValidity": "2019-02-02T09:35:36",
	"dateOfAnnouncement": "2014-01-01T10:10:30",
	"address": {
		"name": "Megha Cafe",
		"number": "874",
		"street": "garhi cantt",
		"city": "Dehradun",
		"state": "Uttarakhand",
		"zipCode": 248003
	},
	"offerDescription": "bin",
	"originalPrice": 10254,
	"discount": 10,
	"offerRating": 0,
	"offerCategories": "Bin",
	"offerTerms": "bin",
	"keywords": "bin",
	"imageURL": null
},
{
	"offerId": "5aebdd2280aff11139e7605b",
	"userId": "megha@gmail.com",
	"offerTitle": "bin02",
	"offerValidity": "2019-02-02T09:38:28",
	"dateOfAnnouncement": "2014-01-01T10:10:30",
	"address": {
		"name": "Megha Cafe",
		"number": "874",
		"street": "garhi cantt",
		"city": "Dehradun",
		"state": "Uttarakhand",
		"zipCode": 248003
	},
	"offerDescription": "bin",
	"originalPrice": 10254,
	"discount": 105,
	"offerRating": 0,
	"offerCategories": "Bin",
	"offerTerms": "bin",
	"keywords": "bin",
	"imageURL": null
},
{
	"offerId": "5aebdd3880aff11139e7605d",
	"userId": "megha@gmail.com",
	"offerTitle": "bin03",
	"offerValidity": "2019-02-02T09:38:50",
	"dateOfAnnouncement": "2014-01-01T10:10:30",
	"address": {
		"name": "Megha Cafe",
		"number": "874",
		"street": "garhi cantt",
		"city": "Dehradun",
		"state": "Uttarakhand",
		"zipCode": 248003
	},
	"offerDescription": "bin",
	"originalPrice": 10254,
	"discount": 105,
	"offerRating": 0,
	"offerCategories": "Bin",
	"offerTerms": "bin",
	"keywords": "bin",
	"imageURL": null
},
{
	"offerId": "5aec1b1b80aff11139e76061",
	"userId": "megha@gmail.com",
	"offerTitle": "bin03",
	"offerValidity": "2019-02-02T14:02:47",
	"dateOfAnnouncement": "2018-04-04T14:02:47",
	"address": null,
	"offerDescription": "bin",
	"originalPrice": 1234,
	"discount": 12,
	"offerRating": 0,
	"offerCategories": "bin",
	"offerTerms": "bin",
	"keywords": "bin",
	"imageURL": null
},
{
	"offerId": "5aec268180aff11139e76063",
	"userId": "megha@gmail.com",
	"offerTitle": "base",
	"offerValidity": "2018-01-01T14:54:08",
	"dateOfAnnouncement": "2018-04-04T14:54:08",
	"address": null,
	"offerDescription": "sdaf",
	"originalPrice": 3,
	"discount": 5,
	"offerRating": 0,
	"offerCategories": "gt",
	"offerTerms": "woisnf",
	"keywords": "damn",
	"imageURL": null
}
]

export const NEG_PRODUCTS_OF_A_VENDOR=[
{
	"offerId": "5ae85e41eb97b43d97258b62",
	"userId": "megha@gmail.com",
	"offerTitle": "Formal Shirt",
	"offerValidity": "2018-04-24T10:04:31.66",
	"address": {
		"name": "Only for You",
		"number": null,
		"street": "Sector 21",
		"city": "Gurgaon",
		"state": "Harayana",
		"zipCode": 122016
	},
	"offerDescription": "Purple solid formal shirt, has a spread collar, button placket, 1 pocket, long sleeves, curved hem Material & Care Cotton and polyester Machine-wash ",
	"originalPrice": 995,
	"discount": 40,
	"offerRating": 4.5,
	"offerCategories": null,
	"offerTerms": "30 days return policy",
	"keywords": "Purple solid formal,  spread collar,  1 pocket",
	"imageURL": "image_url"
},
{
	"offerId": "5ae87704eb97b43d9725be2b",
	"userId": "megha@gmail.com",
	"offerTitle": "Informal Shirt",
	"offerValidity": "2018-04-24T10:04:31.66",
	"dateOfAnnouncement": "2018-04-24T10:04:31.66",
	"address": {
		"name": "Only for You",
		"number": null,
		"street": "Sector 21",
		"city": "Gurgaon",
		"state": "Harayana",
		"zipCode": 122016
	},
	"offerDescription": "Purple solid formal shirt, has a spread collar, button placket, 1 pocket, long sleeves, curved hem Material & Care Cotton and polyester Machine-wash ",
	"originalPrice": 995,
	"discount": 40,
	"offerRating": 4.5,
	"offerCategories": "Clothing",
	"offerTerms": "30 days return policy",
	"keywords": "Purple solid formal,  spread collar,  1 pocket",
	"imageURL": "Solid Formal Shirt"
},
{
	"offerId": "5aea94d0ee9f6508c77be6d4",
	"userId": "megha@gmail.com",
	"offerTitle": "vc",
	"offerValidity": "2018-12-31T10:20:14",
	"dateOfAnnouncement": "2018-04-24T10:04:31.66",
	"address": {
		"name": "Megha Cafe",
		"number": "874",
		"street": "garhi cantt",
		"city": "Dehradun",
		"state": "Uttarakhand",
		"zipCode": 248003
	},
	"offerDescription": "vc",
	"originalPrice": 3,
	"discount": 3,
	"offerRating": 0,
	"offerCategories": "vc",
	"offerTerms": "vc",
	"keywords": "vc",
	"imageURL": null
},
{
	"offerId": "5aea95b3ee9f6508c77be6d6",
	"userId": "megha@gmail.com",
	"offerTitle": "gb",
	"offerValidity": "2018-12-31T10:24:01",
	"dateOfAnnouncement": "2018-04-24T10:04:31.66",
	"address": {
		"name": "Megha Cafe",
		"number": "874",
		"street": "garhi cantt",
		"city": "Dehradun",
		"state": "Uttarakhand",
		"zipCode": 248003
	},
	"offerDescription": "gb",
	"originalPrice": 3,
	"discount": 3,
	"offerRating": 0,
	"offerCategories": "gb",
	"offerTerms": "gb",
	"keywords": "gb",
	"imageURL": null
},
{
	"offerId": "5aebdc7b80aff11139e76059",
	"userId": "megha@gmail.com",
	"offerTitle": "bin",
	"offerValidity": "2019-02-02T09:35:36",
	"dateOfAnnouncement": "2014-01-01T10:10:30",
	"address": {
		"name": "Megha Cafe",
		"number": "874",
		"street": "garhi cantt",
		"city": "Dehradun",
		"state": "Uttarakhand",
		"zipCode": 248003
	},
	"offerDescription": "bin",
	"originalPrice": 10254,
	"discount": 10,
	"offerRating": 0,
	"offerCategories": "Bin",
	"offerTerms": "bin",
	"keywords": "bin",
	"imageURL": null
},
{
	"offerId": "5aebdd2280aff11139e7605b",
	"userId": "megha@gmail.com",
	"offerTitle": "bin02",
	"offerValidity": "2019-02-02T09:38:28",
	"dateOfAnnouncement": "2014-01-01T10:10:30",
	"address": {
		"name": "Megha Cafe",
		"number": "874",
		"street": "garhi cantt",
		"city": "Dehradun",
		"state": "Uttarakhand",
		"zipCode": 248003
	},
	"offerDescription": "bin",
	"originalPrice": 10254,
	"discount": 105,
	"offerRating": 0,
	"offerCategories": "Bin",
	"offerTerms": "bin",
	"keywords": "bin",
	"imageURL": null
},
{
	"offerId": "5aebdd3880aff11139e7605d",
	"userId": "megha@gmail.com",
	"offerTitle": "bin03",
	"offerValidity": "2019-02-02T09:38:50",
	"dateOfAnnouncement": "2014-01-01T10:10:30",
	"address": {
		"name": "Megha Cafe",
		"number": "874",
		"street": "garhi cantt",
		"city": "Dehradun",
		"state": "Uttarakhand",
		"zipCode": 248003
	},
	"offerDescription": "bin",
	"originalPrice": 10254,
	"discount": 105,
	"offerRating": 0,
	"offerCategories": "Bin",
	"offerTerms": "bin",
	"keywords": "bin",
	"imageURL": null
},
{
	"offerId": "5aec1b1b80aff11139e76061",
	"userId": "megha@gmail.com",
	"offerTitle": "bin03",
	"offerValidity": "2019-02-02T14:02:47",
	"dateOfAnnouncement": "2018-04-04T14:02:47",
	"address": null,
	"offerDescription": "bin",
	"originalPrice": 1234,
	"discount": 12,
	"offerRating": 0,
	"offerCategories": "bin",
	"offerTerms": "bin",
	"keywords": "bin",
	"imageURL": null
},
{
	"offerId": "5aec268180aff11139e76063",
	"userId": "megha@gmail.com",
	"offerTitle": "base",
	"offerValidity": "2018-01-01T14:54:08",
	"dateOfAnnouncement": "2018-04-04T14:54:08",
	"address": null,
	"offerDescription": "sdaf",
	"originalPrice": 3,
	"discount": 5,
	"offerRating": 0,
	"offerCategories": "gt",
	"offerTerms": "woisnf",
	"keywords": "damn",
	"imageURL": null
}
]
